// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"orbguard-lab/internal/domain/models"
)

const countActiveCampaigns = `-- name: CountActiveCampaigns :one
SELECT COUNT(*) FROM campaigns WHERE status = 'active'
`

func (q *Queries) CountActiveCampaigns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCampaigns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCampaigns = `-- name: CountCampaigns :one
SELECT COUNT(*) FROM campaigns
`

func (q *Queries) CountCampaigns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCampaigns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMalwareFamilies = `-- name: CountMalwareFamilies :one
SELECT COUNT(*) FROM malware_families
`

func (q *Queries) CountMalwareFamilies(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMalwareFamilies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countThreatActors = `-- name: CountThreatActors :one
SELECT COUNT(*) FROM threat_actors
`

func (q *Queries) CountThreatActors(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countThreatActors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (
    name, slug, description, status,
    threat_actor_id, target_sectors, target_regions, target_platforms,
    mitre_techniques, mitre_tactics,
    first_seen, last_seen, start_date, end_date,
    "references", metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10,
    $11, $12, $13, $14,
    $15, $16
)
RETURNING id, name, slug, description, status, threat_actor_id, target_sectors, target_regions, target_platforms, mitre_techniques, mitre_tactics, first_seen, last_seen, start_date, end_date, indicator_count, "references", metadata, graph_node_id, created_at, updated_at
`

type CreateCampaignParams struct {
	Name            string                `db:"name" json:"name"`
	Slug            string                `db:"slug" json:"slug"`
	Description     pgtype.Text           `db:"description" json:"description"`
	Status          models.CampaignStatus `db:"status" json:"status"`
	ThreatActorID   pgtype.UUID           `db:"threat_actor_id" json:"threat_actor_id"`
	TargetSectors   []string              `db:"target_sectors" json:"target_sectors"`
	TargetRegions   []string              `db:"target_regions" json:"target_regions"`
	TargetPlatforms []string              `db:"target_platforms" json:"target_platforms"`
	MitreTechniques []string              `db:"mitre_techniques" json:"mitre_techniques"`
	MitreTactics    []string              `db:"mitre_tactics" json:"mitre_tactics"`
	FirstSeen       pgtype.Timestamptz    `db:"first_seen" json:"first_seen"`
	LastSeen        pgtype.Timestamptz    `db:"last_seen" json:"last_seen"`
	StartDate       pgtype.Timestamptz    `db:"start_date" json:"start_date"`
	EndDate         pgtype.Timestamptz    `db:"end_date" json:"end_date"`
	References      []string              `db:"references" json:"references"`
	Metadata        []byte                `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg *CreateCampaignParams) (*Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Status,
		arg.ThreatActorID,
		arg.TargetSectors,
		arg.TargetRegions,
		arg.TargetPlatforms,
		arg.MitreTechniques,
		arg.MitreTactics,
		arg.FirstSeen,
		arg.LastSeen,
		arg.StartDate,
		arg.EndDate,
		arg.References,
		arg.Metadata,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.ThreatActorID,
		&i.TargetSectors,
		&i.TargetRegions,
		&i.TargetPlatforms,
		&i.MitreTechniques,
		&i.MitreTactics,
		&i.FirstSeen,
		&i.LastSeen,
		&i.StartDate,
		&i.EndDate,
		&i.IndicatorCount,
		&i.References,
		&i.Metadata,
		&i.GraphNodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createMalwareFamily = `-- name: CreateMalwareFamily :one
INSERT INTO malware_families (
    name, aliases, description, type, platforms,
    threat_actor_id, techniques, capabilities,
    first_seen, last_seen, "references", metadata
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12
)
RETURNING id, name, aliases, description, type, platforms, threat_actor_id, techniques, capabilities, indicator_count, campaign_count, first_seen, last_seen, "references", metadata, graph_node_id, created_at, updated_at
`

type CreateMalwareFamilyParams struct {
	Name          string             `db:"name" json:"name"`
	Aliases       []string           `db:"aliases" json:"aliases"`
	Description   pgtype.Text        `db:"description" json:"description"`
	Type          pgtype.Text        `db:"type" json:"type"`
	Platforms     []string           `db:"platforms" json:"platforms"`
	ThreatActorID pgtype.UUID        `db:"threat_actor_id" json:"threat_actor_id"`
	Techniques    []string           `db:"techniques" json:"techniques"`
	Capabilities  []string           `db:"capabilities" json:"capabilities"`
	FirstSeen     pgtype.Timestamptz `db:"first_seen" json:"first_seen"`
	LastSeen      pgtype.Timestamptz `db:"last_seen" json:"last_seen"`
	References    []string           `db:"references" json:"references"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateMalwareFamily(ctx context.Context, arg *CreateMalwareFamilyParams) (*MalwareFamily, error) {
	row := q.db.QueryRow(ctx, createMalwareFamily,
		arg.Name,
		arg.Aliases,
		arg.Description,
		arg.Type,
		arg.Platforms,
		arg.ThreatActorID,
		arg.Techniques,
		arg.Capabilities,
		arg.FirstSeen,
		arg.LastSeen,
		arg.References,
		arg.Metadata,
	)
	var i MalwareFamily
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Aliases,
		&i.Description,
		&i.Type,
		&i.Platforms,
		&i.ThreatActorID,
		&i.Techniques,
		&i.Capabilities,
		&i.IndicatorCount,
		&i.CampaignCount,
		&i.FirstSeen,
		&i.LastSeen,
		&i.References,
		&i.Metadata,
		&i.GraphNodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createThreatActor = `-- name: CreateThreatActor :one
INSERT INTO threat_actors (
    name, aliases, description, type, motivation, country, active,
    target_sectors, target_regions, common_techniques,
    "references", metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10,
    $11, $12
)
RETURNING id, name, aliases, description, type, motivation, country, active, target_sectors, target_regions, common_techniques, campaign_count, indicator_count, "references", metadata, graph_node_id, created_at, updated_at
`

type CreateThreatActorParams struct {
	Name             string                    `db:"name" json:"name"`
	Aliases          []string                  `db:"aliases" json:"aliases"`
	Description      pgtype.Text               `db:"description" json:"description"`
	Type             models.ThreatActorType    `db:"type" json:"type"`
	Motivation       NullThreatActorMotivation `db:"motivation" json:"motivation"`
	Country          pgtype.Text               `db:"country" json:"country"`
	Active           bool                      `db:"active" json:"active"`
	TargetSectors    []string                  `db:"target_sectors" json:"target_sectors"`
	TargetRegions    []string                  `db:"target_regions" json:"target_regions"`
	CommonTechniques []string                  `db:"common_techniques" json:"common_techniques"`
	References       []string                  `db:"references" json:"references"`
	Metadata         []byte                    `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateThreatActor(ctx context.Context, arg *CreateThreatActorParams) (*ThreatActor, error) {
	row := q.db.QueryRow(ctx, createThreatActor,
		arg.Name,
		arg.Aliases,
		arg.Description,
		arg.Type,
		arg.Motivation,
		arg.Country,
		arg.Active,
		arg.TargetSectors,
		arg.TargetRegions,
		arg.CommonTechniques,
		arg.References,
		arg.Metadata,
	)
	var i ThreatActor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Aliases,
		&i.Description,
		&i.Type,
		&i.Motivation,
		&i.Country,
		&i.Active,
		&i.TargetSectors,
		&i.TargetRegions,
		&i.CommonTechniques,
		&i.CampaignCount,
		&i.IndicatorCount,
		&i.References,
		&i.Metadata,
		&i.GraphNodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM campaigns WHERE id = $1
`

func (q *Queries) DeleteCampaign(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCampaign, id)
	return err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, name, slug, description, status, threat_actor_id, target_sectors, target_regions, target_platforms, mitre_techniques, mitre_tactics, first_seen, last_seen, start_date, end_date, indicator_count, "references", metadata, graph_node_id, created_at, updated_at FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaignByID(ctx context.Context, id uuid.UUID) (*Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByID, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.ThreatActorID,
		&i.TargetSectors,
		&i.TargetRegions,
		&i.TargetPlatforms,
		&i.MitreTechniques,
		&i.MitreTactics,
		&i.FirstSeen,
		&i.LastSeen,
		&i.StartDate,
		&i.EndDate,
		&i.IndicatorCount,
		&i.References,
		&i.Metadata,
		&i.GraphNodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getCampaignBySlug = `-- name: GetCampaignBySlug :one
SELECT id, name, slug, description, status, threat_actor_id, target_sectors, target_regions, target_platforms, mitre_techniques, mitre_tactics, first_seen, last_seen, start_date, end_date, indicator_count, "references", metadata, graph_node_id, created_at, updated_at FROM campaigns WHERE slug = $1
`

func (q *Queries) GetCampaignBySlug(ctx context.Context, slug string) (*Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignBySlug, slug)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.ThreatActorID,
		&i.TargetSectors,
		&i.TargetRegions,
		&i.TargetPlatforms,
		&i.MitreTechniques,
		&i.MitreTactics,
		&i.FirstSeen,
		&i.LastSeen,
		&i.StartDate,
		&i.EndDate,
		&i.IndicatorCount,
		&i.References,
		&i.Metadata,
		&i.GraphNodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMalwareFamilyByID = `-- name: GetMalwareFamilyByID :one

SELECT id, name, aliases, description, type, platforms, threat_actor_id, techniques, capabilities, indicator_count, campaign_count, first_seen, last_seen, "references", metadata, graph_node_id, created_at, updated_at FROM malware_families WHERE id = $1
`

// Malware Families
func (q *Queries) GetMalwareFamilyByID(ctx context.Context, id uuid.UUID) (*MalwareFamily, error) {
	row := q.db.QueryRow(ctx, getMalwareFamilyByID, id)
	var i MalwareFamily
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Aliases,
		&i.Description,
		&i.Type,
		&i.Platforms,
		&i.ThreatActorID,
		&i.Techniques,
		&i.Capabilities,
		&i.IndicatorCount,
		&i.CampaignCount,
		&i.FirstSeen,
		&i.LastSeen,
		&i.References,
		&i.Metadata,
		&i.GraphNodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMalwareFamilyByName = `-- name: GetMalwareFamilyByName :one
SELECT id, name, aliases, description, type, platforms, threat_actor_id, techniques, capabilities, indicator_count, campaign_count, first_seen, last_seen, "references", metadata, graph_node_id, created_at, updated_at FROM malware_families WHERE name = $1
`

func (q *Queries) GetMalwareFamilyByName(ctx context.Context, name string) (*MalwareFamily, error) {
	row := q.db.QueryRow(ctx, getMalwareFamilyByName, name)
	var i MalwareFamily
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Aliases,
		&i.Description,
		&i.Type,
		&i.Platforms,
		&i.ThreatActorID,
		&i.Techniques,
		&i.Capabilities,
		&i.IndicatorCount,
		&i.CampaignCount,
		&i.FirstSeen,
		&i.LastSeen,
		&i.References,
		&i.Metadata,
		&i.GraphNodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getThreatActorByID = `-- name: GetThreatActorByID :one

SELECT id, name, aliases, description, type, motivation, country, active, target_sectors, target_regions, common_techniques, campaign_count, indicator_count, "references", metadata, graph_node_id, created_at, updated_at FROM threat_actors WHERE id = $1
`

// Threat Actors
func (q *Queries) GetThreatActorByID(ctx context.Context, id uuid.UUID) (*ThreatActor, error) {
	row := q.db.QueryRow(ctx, getThreatActorByID, id)
	var i ThreatActor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Aliases,
		&i.Description,
		&i.Type,
		&i.Motivation,
		&i.Country,
		&i.Active,
		&i.TargetSectors,
		&i.TargetRegions,
		&i.CommonTechniques,
		&i.CampaignCount,
		&i.IndicatorCount,
		&i.References,
		&i.Metadata,
		&i.GraphNodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getThreatActorByName = `-- name: GetThreatActorByName :one
SELECT id, name, aliases, description, type, motivation, country, active, target_sectors, target_regions, common_techniques, campaign_count, indicator_count, "references", metadata, graph_node_id, created_at, updated_at FROM threat_actors WHERE name = $1
`

func (q *Queries) GetThreatActorByName(ctx context.Context, name string) (*ThreatActor, error) {
	row := q.db.QueryRow(ctx, getThreatActorByName, name)
	var i ThreatActor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Aliases,
		&i.Description,
		&i.Type,
		&i.Motivation,
		&i.Country,
		&i.Active,
		&i.TargetSectors,
		&i.TargetRegions,
		&i.CommonTechniques,
		&i.CampaignCount,
		&i.IndicatorCount,
		&i.References,
		&i.Metadata,
		&i.GraphNodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listActiveCampaigns = `-- name: ListActiveCampaigns :many
SELECT id, name, slug, description, status, threat_actor_id, target_sectors, target_regions, target_platforms, mitre_techniques, mitre_tactics, first_seen, last_seen, start_date, end_date, indicator_count, "references", metadata, graph_node_id, created_at, updated_at FROM campaigns
WHERE status = 'active'
ORDER BY last_seen DESC
`

func (q *Queries) ListActiveCampaigns(ctx context.Context) ([]*Campaign, error) {
	rows, err := q.db.Query(ctx, listActiveCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.ThreatActorID,
			&i.TargetSectors,
			&i.TargetRegions,
			&i.TargetPlatforms,
			&i.MitreTechniques,
			&i.MitreTactics,
			&i.FirstSeen,
			&i.LastSeen,
			&i.StartDate,
			&i.EndDate,
			&i.IndicatorCount,
			&i.References,
			&i.Metadata,
			&i.GraphNodeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveThreatActors = `-- name: ListActiveThreatActors :many
SELECT id, name, aliases, description, type, motivation, country, active, target_sectors, target_regions, common_techniques, campaign_count, indicator_count, "references", metadata, graph_node_id, created_at, updated_at FROM threat_actors
WHERE active = TRUE
ORDER BY name ASC
`

func (q *Queries) ListActiveThreatActors(ctx context.Context) ([]*ThreatActor, error) {
	rows, err := q.db.Query(ctx, listActiveThreatActors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ThreatActor{}
	for rows.Next() {
		var i ThreatActor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Aliases,
			&i.Description,
			&i.Type,
			&i.Motivation,
			&i.Country,
			&i.Active,
			&i.TargetSectors,
			&i.TargetRegions,
			&i.CommonTechniques,
			&i.CampaignCount,
			&i.IndicatorCount,
			&i.References,
			&i.Metadata,
			&i.GraphNodeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, name, slug, description, status, threat_actor_id, target_sectors, target_regions, target_platforms, mitre_techniques, mitre_tactics, first_seen, last_seen, start_date, end_date, indicator_count, "references", metadata, graph_node_id, created_at, updated_at FROM campaigns
ORDER BY last_seen DESC
`

func (q *Queries) ListCampaigns(ctx context.Context) ([]*Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.ThreatActorID,
			&i.TargetSectors,
			&i.TargetRegions,
			&i.TargetPlatforms,
			&i.MitreTechniques,
			&i.MitreTactics,
			&i.FirstSeen,
			&i.LastSeen,
			&i.StartDate,
			&i.EndDate,
			&i.IndicatorCount,
			&i.References,
			&i.Metadata,
			&i.GraphNodeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMalwareFamilies = `-- name: ListMalwareFamilies :many
SELECT id, name, aliases, description, type, platforms, threat_actor_id, techniques, capabilities, indicator_count, campaign_count, first_seen, last_seen, "references", metadata, graph_node_id, created_at, updated_at FROM malware_families
ORDER BY name ASC
`

func (q *Queries) ListMalwareFamilies(ctx context.Context) ([]*MalwareFamily, error) {
	rows, err := q.db.Query(ctx, listMalwareFamilies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*MalwareFamily{}
	for rows.Next() {
		var i MalwareFamily
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Aliases,
			&i.Description,
			&i.Type,
			&i.Platforms,
			&i.ThreatActorID,
			&i.Techniques,
			&i.Capabilities,
			&i.IndicatorCount,
			&i.CampaignCount,
			&i.FirstSeen,
			&i.LastSeen,
			&i.References,
			&i.Metadata,
			&i.GraphNodeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreatActors = `-- name: ListThreatActors :many
SELECT id, name, aliases, description, type, motivation, country, active, target_sectors, target_regions, common_techniques, campaign_count, indicator_count, "references", metadata, graph_node_id, created_at, updated_at FROM threat_actors
ORDER BY name ASC
`

func (q *Queries) ListThreatActors(ctx context.Context) ([]*ThreatActor, error) {
	rows, err := q.db.Query(ctx, listThreatActors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ThreatActor{}
	for rows.Next() {
		var i ThreatActor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Aliases,
			&i.Description,
			&i.Type,
			&i.Motivation,
			&i.Country,
			&i.Active,
			&i.TargetSectors,
			&i.TargetRegions,
			&i.CommonTechniques,
			&i.CampaignCount,
			&i.IndicatorCount,
			&i.References,
			&i.Metadata,
			&i.GraphNodeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaignIndicatorCount = `-- name: UpdateCampaignIndicatorCount :exec
UPDATE campaigns
SET indicator_count = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateCampaignIndicatorCountParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	IndicatorCount int32     `db:"indicator_count" json:"indicator_count"`
}

func (q *Queries) UpdateCampaignIndicatorCount(ctx context.Context, arg *UpdateCampaignIndicatorCountParams) error {
	_, err := q.db.Exec(ctx, updateCampaignIndicatorCount, arg.ID, arg.IndicatorCount)
	return err
}

const updateCampaignLastSeen = `-- name: UpdateCampaignLastSeen :exec
UPDATE campaigns
SET last_seen = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateCampaignLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateCampaignLastSeen, id)
	return err
}

const updateMalwareFamilyIndicatorCount = `-- name: UpdateMalwareFamilyIndicatorCount :exec
UPDATE malware_families
SET indicator_count = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateMalwareFamilyIndicatorCountParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	IndicatorCount int32     `db:"indicator_count" json:"indicator_count"`
}

func (q *Queries) UpdateMalwareFamilyIndicatorCount(ctx context.Context, arg *UpdateMalwareFamilyIndicatorCountParams) error {
	_, err := q.db.Exec(ctx, updateMalwareFamilyIndicatorCount, arg.ID, arg.IndicatorCount)
	return err
}

const updateThreatActorCampaignCount = `-- name: UpdateThreatActorCampaignCount :exec
UPDATE threat_actors
SET campaign_count = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateThreatActorCampaignCountParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	CampaignCount int32     `db:"campaign_count" json:"campaign_count"`
}

func (q *Queries) UpdateThreatActorCampaignCount(ctx context.Context, arg *UpdateThreatActorCampaignCountParams) error {
	_, err := q.db.Exec(ctx, updateThreatActorCampaignCount, arg.ID, arg.CampaignCount)
	return err
}

const updateThreatActorIndicatorCount = `-- name: UpdateThreatActorIndicatorCount :exec
UPDATE threat_actors
SET indicator_count = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateThreatActorIndicatorCountParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	IndicatorCount int32     `db:"indicator_count" json:"indicator_count"`
}

func (q *Queries) UpdateThreatActorIndicatorCount(ctx context.Context, arg *UpdateThreatActorIndicatorCountParams) error {
	_, err := q.db.Exec(ctx, updateThreatActorIndicatorCount, arg.ID, arg.IndicatorCount)
	return err
}
