package threatintel

// This file contains placeholder types that would normally be generated by protoc.
// In a real implementation, run:
//   protoc --go_out=. --go-grpc_out=. proto/threatintel/v1/threat_intelligence.proto

import (
	"context"

	"github.com/google/uuid"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/timestamppb"

	"orbguard-lab/internal/domain/models"
)

// ThreatIntelligenceServiceServer is the server API for ThreatIntelligenceService service.
type ThreatIntelligenceServiceServer interface {
	CheckIndicators(context.Context, *CheckIndicatorsRequest) (*CheckIndicatorsResponse, error)
	GetThreatStats(context.Context, *GetThreatStatsRequest) (*ThreatStatsResponse, error)
	StreamNewThreats(*StreamThreatsRequest, ThreatIntelligenceService_StreamNewThreatsServer) error
	ShouldBlockDomain(context.Context, *BlockCheckRequest) (*BlockCheckResponse, error)
	ReportNetworkThreat(context.Context, *NetworkThreatReport) (*ReportResponse, error)
	GetIndicator(context.Context, *GetIndicatorRequest) (*GetIndicatorResponse, error)
	ListIndicators(context.Context, *ListIndicatorsRequest) (*ListIndicatorsResponse, error)
	GetCampaign(context.Context, *GetCampaignRequest) (*GetCampaignResponse, error)
	ListCampaigns(context.Context, *ListCampaignsRequest) (*ListCampaignsResponse, error)
	mustEmbedUnimplementedThreatIntelligenceServiceServer()
}

// RegisterThreatIntelligenceServiceServer registers the server with the gRPC server
func RegisterThreatIntelligenceServiceServer(s *grpc.Server, srv ThreatIntelligenceServiceServer) {
	// This would be implemented by generated code
	// For now, this is a placeholder
}

// Streaming interface
type ThreatIntelligenceService_StreamNewThreatsServer interface {
	Send(*ThreatUpdate) error
	grpc.ServerStream
}

// Message types (placeholders - normally generated by protoc)

type IndicatorType int32

const (
	IndicatorType_INDICATOR_TYPE_UNSPECIFIED IndicatorType = 0
	IndicatorType_INDICATOR_TYPE_DOMAIN      IndicatorType = 1
	IndicatorType_INDICATOR_TYPE_IP          IndicatorType = 2
	IndicatorType_INDICATOR_TYPE_IPV6        IndicatorType = 3
	IndicatorType_INDICATOR_TYPE_HASH        IndicatorType = 4
	IndicatorType_INDICATOR_TYPE_URL         IndicatorType = 5
	IndicatorType_INDICATOR_TYPE_PROCESS     IndicatorType = 6
	IndicatorType_INDICATOR_TYPE_CERTIFICATE IndicatorType = 7
	IndicatorType_INDICATOR_TYPE_PACKAGE     IndicatorType = 8
	IndicatorType_INDICATOR_TYPE_EMAIL       IndicatorType = 9
	IndicatorType_INDICATOR_TYPE_FILEPATH    IndicatorType = 10
)

func (i IndicatorType) String() string {
	names := map[IndicatorType]string{
		0: "UNSPECIFIED", 1: "DOMAIN", 2: "IP", 3: "IPV6",
		4: "HASH", 5: "URL", 6: "PROCESS", 7: "CERTIFICATE",
		8: "PACKAGE", 9: "EMAIL", 10: "FILEPATH",
	}
	return names[i]
}

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_INFO        Severity = 1
	Severity_SEVERITY_LOW         Severity = 2
	Severity_SEVERITY_MEDIUM      Severity = 3
	Severity_SEVERITY_HIGH        Severity = 4
	Severity_SEVERITY_CRITICAL    Severity = 5
)

type Platform int32

const (
	Platform_PLATFORM_UNSPECIFIED Platform = 0
	Platform_PLATFORM_ANDROID     Platform = 1
	Platform_PLATFORM_IOS         Platform = 2
	Platform_PLATFORM_WINDOWS     Platform = 3
	Platform_PLATFORM_MACOS       Platform = 4
	Platform_PLATFORM_LINUX       Platform = 5
	Platform_PLATFORM_ALL         Platform = 6
)

type CheckIndicatorsRequest struct {
	Indicators []*CheckIndicator
}

type CheckIndicator struct {
	Value string
	Type  IndicatorType
}

type CheckIndicatorsResponse struct {
	Results []*CheckResult
}

type CheckResult struct {
	Value       string
	Type        IndicatorType
	IsMalicious bool
	Severity    Severity
	Confidence  float64
	Tags        []string
	Description string
	CampaignId  string
}

type GetThreatStatsRequest struct {
	From *timestamppb.Timestamp
	To   *timestamppb.Timestamp
}

type ThreatStatsResponse struct {
	TotalIndicators      int64
	IndicatorsByType     map[string]int64
	IndicatorsBySeverity map[string]int64
	IndicatorsByPlatform map[string]int64
	TotalSources         int32
	ActiveSources        int32
	TotalCampaigns       int32
	ActiveCampaigns      int32
	PegasusIndicators    int64
	MobileIndicators     int64
	CriticalIndicators   int64
	LastUpdate           *timestamppb.Timestamp
	TodayNewIocs         int64
	WeeklyNewIocs        int64
	DataVersion          int64
}

type StreamThreatsRequest struct {
	Types       []IndicatorType
	MinSeverity Severity
	Platforms   []string
	CampaignId  string
	Tags        []string
	PegasusOnly bool
}

type ThreatUpdate struct {
	Id             string
	Type           string
	Timestamp      *timestamppb.Timestamp
	IndicatorId    string
	IndicatorValue string
	IndicatorType  IndicatorType
	Severity       Severity
	Confidence     float64
	Description    string
	Tags           []string
	Platforms      []string
	CampaignId     string
	CampaignName   string
	ThreatActorId  string
	SourceSlug     string
	SourceName     string
}

type Indicator struct {
	Id              string
	Value           string
	Type            IndicatorType
	Severity        Severity
	Confidence      float64
	Description     string
	Tags            []string
	Platforms       []Platform
	FirstSeen       *timestamppb.Timestamp
	LastSeen        *timestamppb.Timestamp
	CampaignId      string
	ThreatActorId   string
	MitreTechniques []string
	ReportCount     int32
	SourceCount     int32
}

type BlockCheckRequest struct {
	Domain   string
	ClientIp string
	ServerId string
}

type BlockCheckResponse struct {
	ShouldBlock bool
	Severity    Severity
	Reason      string
	CampaignId  string
	Tags        []string
	Confidence  float64
}

type NetworkThreatReport struct {
	IndicatorValue  string
	IndicatorType   IndicatorType
	Description     string
	ServerId        string
	ClientIp        string
	DestinationIp   string
	DestinationPort int32
	Protocol        string
	Metadata        map[string]string
}

type ReportResponse struct {
	Success  bool
	Message  string
	ReportId string
}

type GetIndicatorRequest struct {
	Value string
	Type  IndicatorType
}

type GetIndicatorResponse struct {
	Found     bool
	Indicator *Indicator
}

type ListIndicatorsRequest struct {
	Types          []IndicatorType
	Severities     []Severity
	Platforms      []Platform
	Tags           []string
	CampaignId     string
	MinConfidence  float64
	FirstSeenAfter *timestamppb.Timestamp
	LastSeenAfter  *timestamppb.Timestamp
	PegasusOnly    bool
	Limit          int32
	Offset         int32
	Cursor         string
}

type ListIndicatorsResponse struct {
	Indicators []*Indicator
	Total      int64
	HasMore    bool
	NextCursor string
}

type Campaign struct {
	Id              string
	Name            string
	Slug            string
	Description     string
	Status          string
	ThreatActorId   string
	ThreatActorName string
	TargetSectors   []string
	TargetPlatforms []Platform
	MitreTechniques []string
	FirstSeen       *timestamppb.Timestamp
	LastSeen        *timestamppb.Timestamp
	IndicatorCount  int64
}

type GetCampaignRequest struct {
	Id   string
	Slug string
}

type GetCampaignResponse struct {
	Found    bool
	Campaign *Campaign
}

type ListCampaignsRequest struct {
	ActiveOnly bool
	Limit      int32
	Offset     int32
}

type ListCampaignsResponse struct {
	Campaigns []*Campaign
	Total     int64
}

// Helper functions for converting between models and proto types

// modelSeverityToProto converts models.Severity to proto Severity
func modelSeverityToProto(s models.Severity) Severity {
	switch s {
	case models.SeverityInfo:
		return Severity_SEVERITY_INFO
	case models.SeverityLow:
		return Severity_SEVERITY_LOW
	case models.SeverityMedium:
		return Severity_SEVERITY_MEDIUM
	case models.SeverityHigh:
		return Severity_SEVERITY_HIGH
	case models.SeverityCritical:
		return Severity_SEVERITY_CRITICAL
	default:
		return Severity_SEVERITY_UNSPECIFIED
	}
}

// modelTypeToProto converts models.IndicatorType to proto IndicatorType
func modelTypeToProto(t models.IndicatorType) IndicatorType {
	switch t {
	case models.IndicatorTypeDomain:
		return IndicatorType_INDICATOR_TYPE_DOMAIN
	case models.IndicatorTypeIP:
		return IndicatorType_INDICATOR_TYPE_IP
	case models.IndicatorTypeIPv6:
		return IndicatorType_INDICATOR_TYPE_IPV6
	case models.IndicatorTypeHash:
		return IndicatorType_INDICATOR_TYPE_HASH
	case models.IndicatorTypeURL:
		return IndicatorType_INDICATOR_TYPE_URL
	case models.IndicatorTypeProcess:
		return IndicatorType_INDICATOR_TYPE_PROCESS
	case models.IndicatorTypeCertificate:
		return IndicatorType_INDICATOR_TYPE_CERTIFICATE
	case models.IndicatorTypePackage:
		return IndicatorType_INDICATOR_TYPE_PACKAGE
	case models.IndicatorTypeEmail:
		return IndicatorType_INDICATOR_TYPE_EMAIL
	case models.IndicatorTypeFilePath:
		return IndicatorType_INDICATOR_TYPE_FILEPATH
	default:
		return IndicatorType_INDICATOR_TYPE_UNSPECIFIED
	}
}

// protoTypeToModel converts proto IndicatorType to models.IndicatorType
func protoTypeToModel(t IndicatorType) models.IndicatorType {
	switch t {
	case IndicatorType_INDICATOR_TYPE_DOMAIN:
		return models.IndicatorTypeDomain
	case IndicatorType_INDICATOR_TYPE_IP:
		return models.IndicatorTypeIP
	case IndicatorType_INDICATOR_TYPE_IPV6:
		return models.IndicatorTypeIPv6
	case IndicatorType_INDICATOR_TYPE_HASH:
		return models.IndicatorTypeHash
	case IndicatorType_INDICATOR_TYPE_URL:
		return models.IndicatorTypeURL
	case IndicatorType_INDICATOR_TYPE_PROCESS:
		return models.IndicatorTypeProcess
	case IndicatorType_INDICATOR_TYPE_CERTIFICATE:
		return models.IndicatorTypeCertificate
	case IndicatorType_INDICATOR_TYPE_PACKAGE:
		return models.IndicatorTypePackage
	case IndicatorType_INDICATOR_TYPE_EMAIL:
		return models.IndicatorTypeEmail
	case IndicatorType_INDICATOR_TYPE_FILEPATH:
		return models.IndicatorTypeFilePath
	default:
		return ""
	}
}

// protoSeverityToModel converts a single proto Severity to models.Severity
func protoSeverityToModel(s Severity) models.Severity {
	switch s {
	case Severity_SEVERITY_INFO:
		return models.SeverityInfo
	case Severity_SEVERITY_LOW:
		return models.SeverityLow
	case Severity_SEVERITY_MEDIUM:
		return models.SeverityMedium
	case Severity_SEVERITY_HIGH:
		return models.SeverityHigh
	case Severity_SEVERITY_CRITICAL:
		return models.SeverityCritical
	default:
		return ""
	}
}

// protoSeveritiesToModel converts proto Severity slice to models.Severity slice
func protoSeveritiesToModel(severities []Severity) []models.Severity {
	result := make([]models.Severity, 0, len(severities))
	for _, s := range severities {
		switch s {
		case Severity_SEVERITY_INFO:
			result = append(result, models.SeverityInfo)
		case Severity_SEVERITY_LOW:
			result = append(result, models.SeverityLow)
		case Severity_SEVERITY_MEDIUM:
			result = append(result, models.SeverityMedium)
		case Severity_SEVERITY_HIGH:
			result = append(result, models.SeverityHigh)
		case Severity_SEVERITY_CRITICAL:
			result = append(result, models.SeverityCritical)
		}
	}
	return result
}

// protoTypesToModel converts proto IndicatorType slice to models.IndicatorType slice
func protoTypesToModel(types []IndicatorType) []models.IndicatorType {
	result := make([]models.IndicatorType, 0, len(types))
	for _, t := range types {
		if mt := protoTypeToModel(t); mt != "" {
			result = append(result, mt)
		}
	}
	return result
}

// uuidToString converts a uuid.UUID to string, handling nil
func uuidToString(id *uuid.UUID) string {
	if id == nil || *id == uuid.Nil {
		return ""
	}
	return id.String()
}

// modelIndicatorToProto converts a models.Indicator to proto Indicator
func modelIndicatorToProto(i *models.Indicator) *Indicator {
	if i == nil {
		return nil
	}

	platforms := make([]Platform, 0)
	for _, p := range i.Platforms {
		switch p {
		case "android":
			platforms = append(platforms, Platform_PLATFORM_ANDROID)
		case "ios":
			platforms = append(platforms, Platform_PLATFORM_IOS)
		case "windows":
			platforms = append(platforms, Platform_PLATFORM_WINDOWS)
		case "macos":
			platforms = append(platforms, Platform_PLATFORM_MACOS)
		case "linux":
			platforms = append(platforms, Platform_PLATFORM_LINUX)
		case "all":
			platforms = append(platforms, Platform_PLATFORM_ALL)
		}
	}

	return &Indicator{
		Id:              i.ID.String(),
		Value:           i.Value,
		Type:            modelTypeToProto(i.Type),
		Severity:        modelSeverityToProto(i.Severity),
		Confidence:      i.Confidence,
		Description:     i.Description,
		Tags:            i.Tags,
		Platforms:       platforms,
		FirstSeen:       timestamppb.New(i.FirstSeen),
		LastSeen:        timestamppb.New(i.LastSeen),
		CampaignId:      uuidToString(i.CampaignID),
		ThreatActorId:   uuidToString(i.ThreatActorID),
		MitreTechniques: i.MitreTechniques,
		ReportCount:     int32(i.ReportCount),
		SourceCount:     int32(i.SourceCount),
	}
}
