package threatintel

// This file contains placeholder types that would normally be generated by protoc.
// In a real implementation, run:
//   protoc --go_out=. --go-grpc_out=. proto/threatintel/v1/threat_intelligence.proto

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// ThreatIntelligenceServiceServer is the server API for ThreatIntelligenceService service.
type ThreatIntelligenceServiceServer interface {
	CheckIndicators(context.Context, *CheckIndicatorsRequest) (*CheckIndicatorsResponse, error)
	GetThreatStats(context.Context, *GetThreatStatsRequest) (*ThreatStatsResponse, error)
	StreamNewThreats(*StreamThreatsRequest, ThreatIntelligenceService_StreamNewThreatsServer) error
	ShouldBlockDomain(context.Context, *BlockCheckRequest) (*BlockCheckResponse, error)
	ReportNetworkThreat(context.Context, *NetworkThreatReport) (*ReportResponse, error)
	GetIndicator(context.Context, *GetIndicatorRequest) (*GetIndicatorResponse, error)
	ListIndicators(context.Context, *ListIndicatorsRequest) (*ListIndicatorsResponse, error)
	GetCampaign(context.Context, *GetCampaignRequest) (*GetCampaignResponse, error)
	ListCampaigns(context.Context, *ListCampaignsRequest) (*ListCampaignsResponse, error)
	mustEmbedUnimplementedThreatIntelligenceServiceServer()
}

// RegisterThreatIntelligenceServiceServer registers the server with the gRPC server
func RegisterThreatIntelligenceServiceServer(s *grpc.Server, srv ThreatIntelligenceServiceServer) {
	// This would be implemented by generated code
	// For now, this is a placeholder
}

// Streaming interface
type ThreatIntelligenceService_StreamNewThreatsServer interface {
	Send(*ThreatUpdate) error
	grpc.ServerStream
}

// Message types (placeholders - normally generated by protoc)

type IndicatorType int32

const (
	IndicatorType_INDICATOR_TYPE_UNSPECIFIED IndicatorType = 0
	IndicatorType_INDICATOR_TYPE_DOMAIN      IndicatorType = 1
	IndicatorType_INDICATOR_TYPE_IP          IndicatorType = 2
	IndicatorType_INDICATOR_TYPE_IPV6        IndicatorType = 3
	IndicatorType_INDICATOR_TYPE_HASH        IndicatorType = 4
	IndicatorType_INDICATOR_TYPE_URL         IndicatorType = 5
	IndicatorType_INDICATOR_TYPE_PROCESS     IndicatorType = 6
	IndicatorType_INDICATOR_TYPE_CERTIFICATE IndicatorType = 7
	IndicatorType_INDICATOR_TYPE_PACKAGE     IndicatorType = 8
	IndicatorType_INDICATOR_TYPE_EMAIL       IndicatorType = 9
	IndicatorType_INDICATOR_TYPE_FILEPATH    IndicatorType = 10
)

func (i IndicatorType) String() string {
	names := map[IndicatorType]string{
		0: "UNSPECIFIED", 1: "DOMAIN", 2: "IP", 3: "IPV6",
		4: "HASH", 5: "URL", 6: "PROCESS", 7: "CERTIFICATE",
		8: "PACKAGE", 9: "EMAIL", 10: "FILEPATH",
	}
	return names[i]
}

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_INFO        Severity = 1
	Severity_SEVERITY_LOW         Severity = 2
	Severity_SEVERITY_MEDIUM      Severity = 3
	Severity_SEVERITY_HIGH        Severity = 4
	Severity_SEVERITY_CRITICAL    Severity = 5
)

type Platform int32

const (
	Platform_PLATFORM_UNSPECIFIED Platform = 0
	Platform_PLATFORM_ANDROID     Platform = 1
	Platform_PLATFORM_IOS         Platform = 2
	Platform_PLATFORM_WINDOWS     Platform = 3
	Platform_PLATFORM_MACOS       Platform = 4
	Platform_PLATFORM_LINUX       Platform = 5
	Platform_PLATFORM_ALL         Platform = 6
)

type CheckIndicatorsRequest struct {
	Indicators []*CheckIndicator
}

type CheckIndicator struct {
	Value string
	Type  IndicatorType
}

type CheckIndicatorsResponse struct {
	Results []*CheckResult
}

type CheckResult struct {
	Value       string
	Type        IndicatorType
	IsMalicious bool
	Severity    Severity
	Confidence  float64
	Tags        []string
	Description string
	CampaignId  string
}

type GetThreatStatsRequest struct {
	From *timestamppb.Timestamp
	To   *timestamppb.Timestamp
}

type ThreatStatsResponse struct {
	TotalIndicators      int64
	IndicatorsByType     map[string]int64
	IndicatorsBySeverity map[string]int64
	IndicatorsByPlatform map[string]int64
	TotalSources         int32
	ActiveSources        int32
	TotalCampaigns       int32
	ActiveCampaigns      int32
	PegasusIndicators    int64
	MobileIndicators     int64
	CriticalIndicators   int64
	LastUpdate           *timestamppb.Timestamp
	TodayNewIocs         int64
	WeeklyNewIocs        int64
	DataVersion          int64
}

type StreamThreatsRequest struct {
	Types       []IndicatorType
	MinSeverity Severity
	Platforms   []Platform
	CampaignId  string
	PegasusOnly bool
}

type ThreatUpdate struct {
	UpdateType int32
	Indicator  *Indicator
	Timestamp  *timestamppb.Timestamp
}

type Indicator struct {
	Id              string
	Value           string
	Type            IndicatorType
	Severity        Severity
	Confidence      float64
	Description     string
	Tags            []string
	Platforms       []Platform
	FirstSeen       *timestamppb.Timestamp
	LastSeen        *timestamppb.Timestamp
	CampaignId      string
	ThreatActorId   string
	MitreTechniques []string
	ReportCount     int32
	SourceCount     int32
}

type BlockCheckRequest struct {
	Domain   string
	ClientIp string
	ServerId string
}

type BlockCheckResponse struct {
	ShouldBlock bool
	Severity    Severity
	Reason      string
	CampaignId  string
	Tags        []string
	Confidence  float64
}

type NetworkThreatReport struct {
	IndicatorValue  string
	IndicatorType   IndicatorType
	Description     string
	ServerId        string
	ClientIp        string
	DestinationIp   string
	DestinationPort int32
	Protocol        string
	Metadata        map[string]string
}

type ReportResponse struct {
	Success  bool
	Message  string
	ReportId string
}

type GetIndicatorRequest struct {
	Value string
	Type  IndicatorType
}

type GetIndicatorResponse struct {
	Found     bool
	Indicator *Indicator
}

type ListIndicatorsRequest struct {
	Types          []IndicatorType
	Severities     []Severity
	Platforms      []Platform
	Tags           []string
	CampaignId     string
	MinConfidence  float64
	FirstSeenAfter *timestamppb.Timestamp
	LastSeenAfter  *timestamppb.Timestamp
	PegasusOnly    bool
	Limit          int32
	Offset         int32
	Cursor         string
}

type ListIndicatorsResponse struct {
	Indicators []*Indicator
	Total      int64
	HasMore    bool
	NextCursor string
}

type Campaign struct {
	Id              string
	Name            string
	Slug            string
	Description     string
	Status          string
	ThreatActorId   string
	ThreatActorName string
	TargetSectors   []string
	TargetPlatforms []Platform
	MitreTechniques []string
	FirstSeen       *timestamppb.Timestamp
	LastSeen        *timestamppb.Timestamp
	IndicatorCount  int64
}

type GetCampaignRequest struct {
	Id   string
	Slug string
}

type GetCampaignResponse struct {
	Found    bool
	Campaign *Campaign
}

type ListCampaignsRequest struct {
	ActiveOnly bool
	Limit      int32
	Offset     int32
}

type ListCampaignsResponse struct {
	Campaigns []*Campaign
	Total     int64
}
